<?php

declare(strict_types=1);

namespace App\Models;

use App\Enums\CardRarity;
use Database\Factories\SupportCardFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Carbon;
use Illuminate\Support\Collection;

/**
 * A support card as the game publishes it (ADR-0014).
 *
 * Every column is a verbatim field from `support-cards.json`. There is deliberately no composed
 * display name stored here and no foreign key on `char_id`, for the reasons recorded in
 * `2026_09_30_151945_correct_support_card_schema_and_constraints`: the export supplies a character name
 * and an epithet separately, and its `char_id` addresses GameTora's character space, which includes the
 * 9000-block staff who are not in the trainable catalogue.
 *
 * The client's own vocabulary is applied at the view boundary, not stored: the export key
 * `intelligence` renders as `Wit` and `friend` renders as `Pal` (UMAMUSUME_REFERENCE.md §1.4.1).
 *
 * @property int $id
 * @property int $support_id the source's own card id
 * @property int|null $char_id the source's character id, in ITS number space: not a foreign key, and
 *                             9000-block values name staff who have no trainee row at all (FR-A-8)
 * @property string|null $char_name the source's English character name, verbatim
 * @property string|null $name_ja
 * @property string|null $title_en the bracketed epithet, verbatim including its brackets
 * @property string|null $title_ja
 * @property CardRarity $rarity
 * @property string $type one of TYPES, the export's key rather than the client's word
 * @property Carbon|null $release_jp
 * @property Carbon|null $release_global null means `[Global]` has not received this card
 * @property-read string $release_status generated by the column, not computed here
 * @property array<int, array<int, int>> $effects eleven level anchors per effect, `-1` meaning no anchor
 * @property string $source_url
 * @property Carbon $fetched_at
 * @property bool $is_manual the Trainer's own correction; the engine's stop sign (FR-B-4)
 * @property-read Collection<int, DeckSlot> $deckSlots
 */
#[Fillable(['support_id', 'char_id', 'char_name', 'name_ja', 'title_en', 'title_ja', 'rarity', 'type', 'release_jp', 'release_global', 'effects', 'source_url', 'fetched_at', 'is_manual'])]
class SupportCard extends Model
{
    /** @use HasFactory<SupportCardFactory> */
    use HasFactory;

    /**
     * The seven export type keys. Held as a constant because the migration's CHECK, the import parser
     * and the picker all have to agree with it, and a list that lives in only one of them drifts.
     */
    public const TYPES = ['speed', 'stamina', 'power', 'guts', 'intelligence', 'friend', 'group'];

    protected function casts(): array
    {
        return [
            'support_id' => 'integer',
            'char_id' => 'integer',
            'rarity' => CardRarity::class,
            'release_jp' => 'date',
            'release_global' => 'date',
            'effects' => 'array',
            'fetched_at' => 'datetime',
            'is_manual' => 'boolean',
        ];
    }

    /**
     * @return HasMany<DeckSlot, $this>
     */
    public function deckSlots(): HasMany
    {
        return $this->hasMany(DeckSlot::class);
    }

    /**
     * The label a Trainer reads: the character's name plus the card's epithet, as the client prints
     * the two on a card face ("Special Week [Tracen Academy]").
     */
    public function displayName(): string
    {
        $name = $this->char_name ?? $this->name_ja ?? "Card {$this->support_id}";

        return $this->title_en === null ? $name : "{$name} {$this->title_en}";
    }

    /**
     * The client's rarity word, which is not the enum's label. `CardRarity::label()` reads "Three
     * stars" (the order signal `x-rarity-chip` puts in its aria-label); the word the Global client
     * prints is R / SR / SSR (UMAMUSUME_REFERENCE.md §1.4.2), and showing "Three stars" where the game
     * shows "SSR" would be the tool inventing vocabulary.
     */
    public function rarityWord(): string
    {
        return match ($this->rarity) {
            CardRarity::OneStar => 'R',
            CardRarity::TwoStar => 'SR',
            CardRarity::ThreeStar => 'SSR',
        };
    }

    /**
     * The client's word for the export's type key. `intelligence` is Wit and `friend` is Pal; neither
     * export key is what the Global client labels the facility with.
     */
    public function typeLabel(): string
    {
        return match ($this->type) {
            'intelligence' => 'Wit',
            'friend' => 'Pal',
            default => ucfirst($this->type),
        };
    }

    public function isFriendType(): bool
    {
        return $this->type === 'friend';
    }

    public function isGroupType(): bool
    {
        return $this->type === 'group';
    }

    /**
     * Is this card the one the running scenario badges as a Scenario Link?
     *
     * Derived, never stored (ADR-0014 correction 3): the badge is a join between the card's character
     * and the scenario's linked list, and it changes when the scenario does. That list is keyed by name
     * in `config('scenarios.php')`, so the match is on the character's name.
     *
     * `group` cards are the known weakness: `training_events__group.json` records six characters behind
     * one card while the card carries a single `char_id`, so a group card badged on a member who is not
     * its representative would be missed here. ADR-0005's re-verification reached the same conclusion
     * and left it open on purpose; no captured frame yet shows a badged group card.
     */
    public function isScenarioLink(string $scenarioKey): bool
    {
        $linked = config("scenarios.scenarios.{$scenarioKey}.scenario_links", []);

        if (! is_array($linked) || $this->char_name === null) {
            return false;
        }

        return in_array($this->char_name, $linked, true);
    }
}
